# Generated by Django 3.2.5 on 2021-09-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacks',
            old_name='user_id',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='username',
        ),
    ]
